#!/usr/bin/perl
# Copyright (c) 2015 Dylan B Storey

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
use warnings;
use strict;
use Getopt::Long;
use POSIX qw/ceil/;
use File::Basename;
use File::Copy;
use File::Spec;

use Data::Dumper;

my $dirname = dirname(__FILE__);

my @files = ();
my $threads = 8;
my $help = 0; 

GetOptions(
	'files=s@{,}' => \@files,
	'help+' => \$help,
	'h+' => \$help,
	'threads' => \$threads
	) || die usage();

die usage() if ($help);
die usage() unless (@files && $threads);

my $chunk_size = (scalar(@files) ** 2) ;
$chunk_size /= $threads*2;
$chunk_size = int($chunk_size);


my $files = join(' ' , @files);



system("perl $dirname/MakeChunks --files $files --chunk_size $chunk_size");
system("parallel --gnu --plain '$dirname/CalculateDistances --manifest {}' ::: *.man");



sub usage{
	print "Dumb wrapper for running pancake on a single machine\n";
	print "Usage:\n";
	print " ./PanCake --threads <int> --files <files>\n";
	}
