#!/usr/bin/perl
# Copyright (c) 2015 Dylan B Storey

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
use warnings;
use strict;
use Getopt::Long;
use POSIX qw/ceil/;
use File::Basename;
use File::Copy;

my @files;
my $chunk_size;

GetOptions(
	'files=s@{,}' => \@files,
	'chunk_size=i' => \$chunk_size
	) || die $!;

$chunk_size //= 10,000;

my $chunk_number = 0;
my $current_chunk_size=0;
open (OUT , '>' , "$chunk_number.man") || die $!;

for ( my $i = 0 ; $i < @files ; $i++){
	for (my $j=$i; $j < @files; $j++){
		print OUT join("\t", ($files[$i] , $files[$j])) . "\n";
		$current_chunk_size++;
		if ($current_chunk_size == $chunk_size){
			close OUT;
			$chunk_number++;
			$current_chunk_size = 0;
			open (OUT , '>' , "$chunk_number.man") || die $!;			
			}
		}
	}





exit;
